development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: rails_test_production
  user: root
  password: jfgg89894dfjkhg
  pool: 5
  timeout: 5000
